# Site settings
title: JMedium 
description: "A technology journal by Jithesh Chandrasekharan"
baseurl: "" 
url: "https://jithesh.io" 
tagline: "Spice up your coding!"

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 6
paginate_path: 'page:num/'
permalink: :title/
gems :
  - jekyll-paginate
  - jekyll-seo-tag
