# Site settings
title: That Pointer -  A Technology journal.
email: jitheshc@gmail.com
description: My experiments with Bigdata technologies.
url: "http://datapetals.com" # the base hostname & protocol for your site
twitter_username: jitheshmenon
github_username: gitjit
paginate: 4
#excerpt_separator: <!--more-->

# Build settings
permalink: /:title
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true
  
# need to install > gem install jekyll-paginate
gems :
  - jekyll-paginate

