# Site settings
title: GitJit - A Bigdata technology journal.
email: jitheshc@gmail.com
description: My experiments and experience on Bigdata technologies.
url: "http://gitjit.com" # the base hostname & protocol for your site
twitter_username: jitheshmenon
github_username: gitjit
paginate: 3

# Build settings
permalink: /:title
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  

gems :
  - jekyll-paginate