# Site settings
title: JMedium 
description: "A technology blog by Jithesh Chandrasekharan"
baseurl: "" 
url: "http://jmedium.com" 
tagline: "Spice up your coding!"

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: 'page:num/'
permalink: :title/
gems :
  - jekyll-paginate
  - jekyll-seo-tag
